### ISSUE TITLE
toPyDateTime().timestamp() can throw OSError

### ISSUE THREAD

**Issue by nicogodet** [vcloarec/meshflow#1]
ref. https://docs.python.org/3/library/datetime.html#datetime.datetime.timestamp

Some telemac model have an initial date in 1900, a simple fix is to set a reference time after 1970

**Comment by vcloarec** [comment]
Hi @nicogodet and welcome here!
Indeed... And there also other formats that has date before 1970...
Thanks to report it, and feel free to purpose a fix. Otherwise, I will do it later.

**Comment by nicogodet** [comment]
Hi @vcloarec 
This ticket was quite brutal I admit, sorry 

I'm really busy right now so I created it as a reminder ;)
I will do some PRs soon !
