### ISSUE TITLE
Add icon to plugin toolbar and/or mesh menu

### ISSUE THREAD

**Issue by nicogodet** [vcloarec/meshflow#4]

**Comment by vcloarec** [comment]
hmm, but I don't see what the action in the menu or associated to a button of the tool bar  will trigger in the menu.

**Comment by nicogodet** [comment]
To be honest, once I close the dockwidget, I couldn't fine another way to reopen it than unload/load the extension...
I could miss something

**Comment by vcloarec** [comment]
My way is not ueser friendly : right click neat the tool bar on the top of QGIS, and check the "Mesh Flow Pannel". 
Indeed, a checkable action in the Mesh Menu linked to the "Mesh Flow" dock widget will be more convenient.
I will look at later.

**Comment by vcloarec** [comment]
done in https://github.com/vcloarec/meshflow/commit/c2aa890d3e9821e5575007be3d7dfd4452fbc781
